/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2015-01-08 14:54:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.status;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import net.mineSQL.util.SessionWatcher;
import net.mineSQL.util.ApplicationWatcher;
import net.mineSQL.connection.ConnectionManager;
import java.util.Iterator;
import java.util.HashMap;

public final class systemStatus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=iso-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

if (request.getParameter("foo") != null) {
    return; // Stop request
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>System Status</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<p align=\"center\">\r\n");
      out.write("    <h3>Application</h3>\r\n");
      out.write("    Vesrion: ");
      out.print( ApplicationWatcher.version );
      out.write("<br/>\r\n");
      out.write("\tHosted on: ");
      out.print( ApplicationWatcher.hostName);
      out.write("<br/>\r\n");
      out.write("    Started on: ");
      out.print( ApplicationWatcher.applicationStarDate);
      out.write("<br/>\r\n");
      out.write("\t\r\n");
      out.write("    <h3>Sessions</h3>\r\n");
      out.write("    Actives : ");
      out.print( SessionWatcher.getActiveSessions() );
      out.write("<br/>\r\n");
      out.write("\t");

    // Scorro tutte le sessioni
	Iterator it = SessionWatcher.getSessions().keySet().iterator();
	while (it.hasNext()){
		String key = (String)it.next();
        out.write("<b>ID:</b> "+key+" ");
        // Stampo dettagli della sessione 
		HashMap ses = SessionWatcher.getSession(key);
        Iterator ises = ses.keySet().iterator();
        while (ises.hasNext()){
            String k = (String)ises.next();
            out.write("<b>"+k+":</b> "+ses.get(k)+"  ");
        }
        out.write("<br/>");
	}
	
      out.write("\r\n");
      out.write("    <h3>Connections</h3>\r\n");
      out.write("    Appended : ");
      out.print( ConnectionManager.getCurrentConnection() );
      out.write("<br/> \r\n");
      out.write("\t</p>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
