/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2015-01-08 14:20:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Vector;
import java.util.*;
import java.net.*;
import java.sql.*;
import java.sql.Timestamp;
import net.mineSQL.controller.UtenteServlet;
import net.mineSQL.util.Utilita;
import net.mineSQL.util.SessionWatcher;
import net.mineSQL.util.ApplicationWatcher;
import java.util.GregorianCalendar;
import org.apache.log4j.Logger;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//IT\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");

String listaUtenti = null;
String listaAree = null;
String listaStati = null;
Logger log = Logger.getLogger("main.jsp");
String user = "";
String group = "";
String idruolo = "";
String groups = "";
String idreparto = "";
String nomeReparto = "";
String nomeRuolo = "";

boolean CONTROLLO_ACCESSO = false;

if (CONTROLLO_ACCESSO){	
	if (request.getSession().getAttribute("IDUTENTE") == null || 
		request.getSession().getAttribute("IDUTENTE").toString().length() == 0 ||
		! request.isRequestedSessionIdValid())
    {
        response.sendRedirect("/index.jsp");
        return;
    }

    try {
        user = session.getAttribute("username").toString();
        group = session.getAttribute("groupname").toString();
        groups = UtenteServlet.getUserGroupJson(user, group);
        // Il ruolo serve per gestire nella MainView la visualizzazione del menu di Admin
        idruolo = session.getAttribute("IDRUOLO").toString();
        // Il reparto condiziona l'abilitazione del bottone "Crea nuovo problem"
        idreparto = session.getAttribute("IDREPARTO").toString();
        nomeReparto = session.getAttribute("NOME_REPARTO").toString();
        nomeRuolo = session.getAttribute("NOME_RUOLO").toString();
        
    }
    catch (NullPointerException ex) {
        log.error(" Error on main page");
    }

}else{
    user = "user";
    group = "0";
    idruolo = "0";
    groups = "[]";
}

log.debug(" session.getId(): " + session.getId());
log.debug(" -------------------> request.getRemoteAddr(): " + request.getRemoteAddr());
SessionWatcher.addSession(session.getId(),"remoteAddress",request.getRemoteAddr());

String urlToGo = "/UtenteServlet";


/*
String valore(String nomeCampo) {
	if (nomeCampo.equals("id_area")) return listaAree; 
	if (nomeCampo.equals("id_utente")) return listaUtenti;
	if (nomeCampo.equals("stato")) return listaStati;
	return "";
}
	*/

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("    <META name=\"language\" content=\"it\">\r\n");
      out.write("    <META Http-Equiv=\"Cache-Control\" Content=\"no-cache\">\r\n");
      out.write("\t<META Http-Equiv=\"Pragma\" Content=\"no-cache\">\r\n");
      out.write("\t<META Http-Equiv=\"Expires\" Content=\"0\">\r\n");
      out.write("\t\r\n");
      out.write("    <title>DB Mining System - Beta</title>\r\n");
      out.write("    <!-- Ext requirement -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"ext-3.4.0/resources/css/ext-all.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"ext-3.4.0/resources/css/xtheme-gray.css\" />\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\" src=\"ext-3.4.0/adapter/ext/ext-base.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"ext-3.4.0/ext-all-debug.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- script type=\"text/javascript\" src=\"http://openlayers.org/api/2.10/OpenLayers.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"GeoExt/lib/GeoExt.js\"></script -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Ext Additional Plugin -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/ext-plugin/RemoteValidator.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/ext-plugin/RowExpander.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/ext-plugin/GroupSummary.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/ext-plugin/SearchField.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/ext-plugin/TableGrid.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/ext-plugin/FieldEnh.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/ext-plugin/DateFieldEnh.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/ext-plugin/HtmlEditorEnh.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/ext-plugin/FileUploadField.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/al.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Griglie e componenti correlati -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/grid/GridFilter.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/grid/GridSearch.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/grid/GridToolbar.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/grid/EditableItem.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/grid/GridFilters.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/grid/filter/Filter.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/grid/filter/ListFilter.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/grid/filter/StringFilter.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/grid/GridAdvancedFilters.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/grid/AutoGrid.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/windows/ScriptSQL.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/windows/iSQL.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/windows/UploadWindow.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/windows/WindowFormTable.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/GenericMenu.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/MainView.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/GenericMenu.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/FilterMngr.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/CSVMngr.js\"></script>\r\n");
      out.write("    <!-- i css servono per correggere dei bug di extjs -->\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("    <link type=\"text/css\" rel=\"stylesheet\" href=\"css/mineSQL.css\" />\r\n");
      out.write("    \r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("\t\t.x-grid3-hd-row td.ux-filtered-column {   \r\n");
      out.write("        font-style: italic;  \r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("    }\t\t\r\n");
      out.write("\t</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Configurazione ambiente e variabile globali -->\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        var ACTIVATE_DEBUG_LOG = false;\r\n");
      out.write("        var RUOLO_SUPERUSER = 'RUOLO_2';\r\n");
      out.write("\r\n");
      out.write("        var ID_FLUSSO_PROBLEM   = 1;\r\n");
      out.write("        var ID_FLUSSO_DEFECT    = 3;\r\n");
      out.write("        var ID_FLUSSO_WORKAROUND= 2;\r\n");
      out.write("        var ID_FLUSSO_TASK      = 4;\r\n");
      out.write("        var ID_FLUSSO_GENERIC   = 5;\r\n");
      out.write("        var RUOLO_READONLY      = \"3\";\r\n");
      out.write("        var RUOLO_READWRITEONLY = \"4\";\r\n");
      out.write("\r\n");
      out.write("        var HOST = \"");
      out.print(request.getServerName()+ ":" + request.getServerPort());
      out.write("\";\r\n");
      out.write("        var USER_NAME = \"");
      out.print(user);
      out.write("\";\r\n");
      out.write("        var USER_GROUP= \"");
      out.print(group);
      out.write("\";\r\n");
      out.write("        var USER_NOME_RUOLO = \"");
      out.print(nomeRuolo);
      out.write("\";\r\n");
      out.write("        var USER_IDREPARTO = \"");
      out.print(idreparto);
      out.write("\";\r\n");
      out.write("        var USER_NOME_REPARTO= \"");
      out.print(nomeReparto);
      out.write("\";\r\n");
      out.write("        var HOST_NAME = \"");
      out.print(ApplicationWatcher.hostName);
      out.write("\";\r\n");
      out.write("        var DM_VERSION = \"");
      out.print(ApplicationWatcher.version);
      out.write("\";\r\n");
      out.write("        var USER_IDRUOLO = \"");
      out.print(idruolo);
      out.write("\";\r\n");
      out.write("        gruppiDisponibili = ");
      out.print(groups);
      out.write(";\r\n");
      out.write("        /*\r\n");
      out.write("         * Tutti i filtri in sessione\r\n");
      out.write("         */\r\n");
      out.write("        SessionFilters = {};\r\n");
      out.write("        SessionFilters[ID_FLUSSO_PROBLEM] = {};\r\n");
      out.write("        SessionFilters[ID_FLUSSO_DEFECT] = {};\r\n");
      out.write("        SessionFilters[ID_FLUSSO_WORKAROUND] = {};\r\n");
      out.write("        SessionFilters[ID_FLUSSO_TASK] = {};\r\n");
      out.write("        \r\n");
      out.write("        /**\r\n");
      out.write("         * Stampa messaggi d'errore nella console javascript  \r\n");
      out.write("         **/\r\n");
      out.write("        function debug(string){\r\n");
      out.write("            if (ACTIVATE_DEBUG_LOG){\r\n");
      out.write("                try     { console.log(this +\": \" +string); } \r\n");
      out.write("                catch(e){ }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        var maxInactiveInterval = ");
      out.print(session.getMaxInactiveInterval());
      out.write(";\r\n");
      out.write("        var tplCombo = \r\n");
      out.write("                new Ext.XTemplate('<tpl for=\".\"><div ext:qtip=\"{ID}. {NOME}\" class=\"x-combo-list-item\">{NOME}</div></tpl>');\r\n");
      out.write("        function openWindows(){\r\n");
      out.write("                ScriptSQL.openWindow();\r\n");
      out.write("    //            iSQL.openWindow();\r\n");
      out.write("        }\r\n");
      out.write("        /**\r\n");
      out.write("         * Definisce la versione corrette dell'applicazione\r\n");
      out.write("         */\r\n");
      out.write("        function setVersion(ver){\r\n");
      out.write("            Ext.get('versione').update(ver);\r\n");
      out.write("        }\r\n");
      out.write("        /**\r\n");
      out.write("        * Short hand\r\n");
      out.write("        */ \r\n");
      out.write("        $ = Ext.get;\r\n");
      out.write("        $$ = Ext.getCmp;\r\n");
      out.write("        /**\r\n");
      out.write("         * Init quick tips\r\n");
      out.write("         */\r\n");
      out.write("        Ext.QuickTips.init();\r\n");
      out.write("\r\n");
      out.write("        /*\r\n");
      out.write("        * Go to main page\r\n");
      out.write("        */ \r\n");
      out.write("        function viewMain(){\r\n");
      out.write("            window.location.href=\"http://");
out.write(request.getServerName()+ ":" + request.getServerPort());
      out.write("/UtenteServlet\";\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /**\r\n");
      out.write("        * Check if current user is limited to disable various buttons\r\n");
      out.write("        */\r\n");
      out.write("        function isLimitedUser(){\r\n");
      out.write("            if ( USER_IDRUOLO == RUOLO_READONLY || \r\n");
      out.write("                 USER_IDRUOLO == RUOLO_READWRITEONLY)\r\n");
      out.write("                return true;\r\n");
      out.write("            else\r\n");
      out.write("                return false;\r\n");
      out.write("        } \r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("<div id=\"contenitore\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    <div id=\"intestazione\">\r\n");
      out.write("\t    <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" bordercolor=\"green\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t  <td colspan=\"3\">\r\n");
      out.write("\t\t\t\t<table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t  <td width=\"477\">\r\n");
      out.write("\t\t\t\t\t\t<table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" border=\"0\" bordercolor=\"red\">\r\n");
      out.write("\t\t\t\t\t\t  <tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td height=\"62\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t  <!-- img hspace=\"0\" src=\"http://recensioni-videogiochi.dvd.it/images/world_in_conflict/world-in-conflict-3-m.jpg\" width=\"477\"  height=\"62\" border=\"0\" align=\"top\" -->\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t  </tr>\r\n");
      out.write("\t\t\t\t\t\t  <tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td height=\"25\" width=\"100%\">\r\n");
      out.write("                                <!-- Form fittizia usata per effettuare il cambio gruppo, ricarica la pagina -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<form name=\"groupForm\" action=\"");
      out.print(urlToGo);
      out.write("\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"username\" value=\"");
      out.print(user);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"idgruppo\" name=\"idgruppo\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"RUOLO_");
      out.print(idruolo);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"operazione\" value=\"CHOICE\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"onchange\" value=\"null\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t  </tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t  </td>\r\n");
      out.write("\t\t\t\t\t  <td width=\"100%\"></td>\r\n");
      out.write("\t\t\t\t\t  <td width=\"93\"><!--img hspace=\"0\" src=\"img/Bottom_Sx.gif\" width=\"199\" height=\"87\" border=\"0\" align=\"top\"--></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t  </td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Corpo centrale -->\r\n");
      out.write("        <div id=\"sommario\">\r\n");
      out.write("        \t\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Main Body, filled with ExtJS -->\r\n");
      out.write("        <div id=\"corpo\">\r\n");
      out.write("            <div id=\"principale\"></div>\r\n");
      out.write("            <div id=\"secondario\"></div>\r\n");
      out.write("            <div id=\"fi-form\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"esclusiva\" class=\"execute\"></div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
